# Generated by Django 5.1 on 2025-02-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('cards', '0008_alter_creditcard_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='card_issuers',
            field=models.ManyToManyField(related_name='card_issuers', to='cards.cardissuer'),
        ),
        migrations.AddField(
            model_name='section',
            name='credit_Cards',
            field=models.ManyToManyField(related_name='credit_cards', to='cards.creditcard'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('heading', 'Heading'), ('subheading', 'Subheading'), ('paragraph', 'Paragraph'), ('image', 'Image'), ('data', 'Data'), ('content', 'Content'), ('custom', 'Custom')], max_length=20),
        ),
    ]
