# Generated by Django 5.1 on 2025-02-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_description'),
        ('cards', '0008_alter_creditcard_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='media/posts/images/'),
        ),
        migrations.AlterField(
            model_name='section',
            name='card_issuers',
            field=models.ManyToManyField(blank=True, related_name='card_issuers', to='cards.cardissuer'),
        ),
        migrations.AlterField(
            model_name='section',
            name='credit_Cards',
            field=models.ManyToManyField(blank=True, related_name='credit_cards', to='cards.creditcard'),
        ),
        migrations.AddField(
            model_name='post',
            name='metaKeywords',
            field=models.ManyToManyField(to='blog.metakeywords'),
        ),
    ]
