# Generated by Django 5.1 on 2025-02-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_metakeywords_post_cover_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='metaKeywords',
            new_name='meta_keywords',
        ),
    ]
