# Generated by Django 5.1.1 on 2024-09-10 17:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('category_description', models.TextField(blank=True, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('category_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('cards_image', models.ImageField(blank=True, null=True, upload_to='cards_images/')),
                ('cards_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('cards_description', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=120, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardIssuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('issuer_image', models.ImageField(blank=True, null=True, upload_to='issuer_images/')),
                ('issuer_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('cards_image', models.ImageField(blank=True, null=True, upload_to='cards_images/')),
                ('cards_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('issuer_description', models.TextField(blank=True, null=True)),
                ('cards_description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('card_type', models.CharField(choices=[('RUPAY', 'RuPay'), ('VISA', 'Visa'), ('MASTERCARD', 'MasterCard'), ('AMEX', 'American Express')], max_length=20)),
                ('annual_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('joining_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rewards_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rewards_type', models.CharField(blank=True, choices=[('POINTS', 'Points'), ('MILES', 'Miles'), ('CASHBACK', 'Cashback')], max_length=20, null=True)),
                ('reward_redemption', models.TextField(blank=True, null=True)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='card_images/')),
                ('card_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('ideal_for', models.CharField(blank=True, max_length=255, null=True)),
                ('welcome_benefit', models.TextField(blank=True, null=True)),
                ('movie_benefits', models.TextField(blank=True, null=True)),
                ('dining_benefits', models.TextField(blank=True, null=True)),
                ('travel_benefits', models.TextField(blank=True, null=True)),
                ('domestic_lounge_access', models.TextField(blank=True, null=True)),
                ('international_lounge_access', models.TextField(blank=True, null=True)),
                ('golf_benefits', models.TextField(blank=True, null=True)),
                ('insurance_benefits', models.TextField(blank=True, null=True)),
                ('spend_based_waiver', models.TextField(blank=True, null=True)),
                ('foreign_currency_markup', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fuel_surcharge', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cash_advance_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('card_details', models.TextField(blank=True, null=True)),
                ('pros', models.TextField(blank=True, null=True)),
                ('cons', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('apply_now_url', models.URLField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('popular', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=120, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('card_upload_date', models.DateField(default=django.utils.timezone.now)),
                ('card_category', models.ManyToManyField(related_name='credit_cards', to='cards.cardcategory')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr', to='cards.cardissuer')),
            ],
        ),
        migrations.AddField(
            model_name='cardissuer',
            name='credit_cards',
            field=models.ManyToManyField(blank=True, related_name='issuers', to='cards.creditcard'),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_faqs', to='cards.cardcategory')),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_faqs', to='cards.cardissuer')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('conclusion', models.TextField()),
                ('image', models.ImageField(blank=True, default='post_images/default_image.jpg', null=True, upload_to='post_images/')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_cards', models.ManyToManyField(related_name='posts', to='cards.creditcard')),
            ],
        ),
    ]
