# Generated by Django 5.1.1 on 2024-09-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_creditcard_renewal_fee_alter_creditcard_annual_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
