# Generated by Django 5.1.1 on 2024-09-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_creditcard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
