# Generated by Django 5.1.1 on 2024-09-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_creditcard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(blank=True, choices=[('RUPAY', 'RuPay'), ('VISA', 'Visa'), ('MASTERCARD', 'MasterCard'), ('AMEX', 'American Express')], max_length=20, null=True),
        ),
    ]
