# Generated by Django 5.1.1 on 2024-09-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_creditcard_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcategory',
            name='heading',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardissuer',
            name='heading',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='document_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='eligibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardissuer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
