# Generated by Django 5.1.1 on 2024-09-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_cardcategory_heading_cardissuer_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
