# Generated by Django 5.1.1 on 2024-09-12 10:51

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_creditcard_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to=cards.models.card_image_upload_path),
        ),
    ]
